### PR TITLE
Jobs section implementation

### PR DESCRIPTION
**Pull request by Vahe83**
Components were created based on fake job data. It will be necessary to replace job data with new ones when those will be available.

### CODE REVIEW

**Comment by nairihar** [comment]
Hi @Vahe83, thanks for the PR,
Could you please make job items clickable, so the URL can be taken from JobList.
Also, can you move the items to center for mobile devices?

**Comment by Vahe83** [comment]
Hi @nairihar,

Sure, I could. I will inform you when I finished.

**Comment by nairihar** [comment]
@Vahe83 jan, I'm going to merge this PR because I have just pushed that changes))

**Comment by Vahe83** [comment]
@nairihar jan thank you.

**Pull request merged**
