### PR TITLE
Location section 

### PR DESCRIPTION
**Pull request by VamOSGS**
image

### CODE REVIEW

**Comment by nairihar** [comment]
@VamOSGS seems there is a problem with the background when the screen size is smaller.
screen shot 2019-01-31 at 12 04 37 am

**Comment by VamOSGS** [comment]
@nairihar already working on that

**Comment by VamOSGS** [comment]
@nairihar I fixed splash on small screens, but its not building because we have eslint error in Title component

image

**Comment by nairihar** [comment]
@VamOSGS can you merge with the master branch? Is it already up to date?

**Comment by VamOSGS** [comment]
@nairihar it's already up to date.

**Comment by nairihar** [comment]
ok @VamOSGS, 
you can see the correct implementation here 
https://github.com/JSConfArmenia/conf-19-react/pull/40/files
just change the function.

**Comment by VamOSGS** [comment]
@nairihar done.

**Comment by nairihar** [comment]
@VamOSGS seems there is again some problems,

could you please change section size?
also, change the max/min @media values, make row a little earlier(when decreasing window size).

screen shot 2019-02-02 at 8 07 04 pm
screen shot 2019-02-02 at 8 07 31 pm

**Comment by VamOSGS** [comment]
@nairihar I am making Location section, maybe you confused it with About sections PR

**Comment by nairihar** [comment]
yes @VamOSGS, I confused it)

**Pull request merged**
